version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: |
           wget https://github.com/MihailJP/Inconsolata-LGC/releases/download/LGC-1.3.0/InconsolataLGC-1.3.0.tar.xz
           tar -xvf InconsolataLGC-1.3.0.tar.xz
           mkdir -p /usr/share/fonts/truetype/inconsolatalgc/
           mv InconsolataLGC/*.ttf /usr/share/fonts/truetype/inconsolatalgc/
           wget https://github.com/khaledhosny/libertinus/releases/download/v6.5/libertinus-6.5.zip
           unzip libertinus-6.5.zip
           mkdir -p /usr/share/fonts/truetype/libertinus/
           apt-get -qq update && apt-get install -y --no-install-recommends fonts-linuxlibertine
       - run: cd src && make
       - store_artifacts:
           path: "category-theory-for-programmers.pdf"
           path: "src/ctfp.log"